---
version: "2.0"
services:
  app:
    image: cvpfus/heurist-miner:0.3
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - MINER_ID_0=0x544476DB6C3514a456e32F9436490B99395A3031
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 1000
deployment:
  app:
    akash:
      profile: app
      count: 1
