---
version: "2.0"
services:
  app:
    image: cvpfus/heurist-miner:0.7
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 8000
        as: 8000
        proto: tcp
        to:
          - global: true
    command:
      - sh
      - "-c"
    args:
      - ./llm-miner-starter.sh $MODEL_NAME; sleep infinity
    env:
      - MODEL_NAME=mistralai/mixtral-8x7b-instruct-v0.1
      - MINER_ID_0=0x544476DB6C3514a456e32F9436490B99395A3031
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 1000
deployment:
  app:
    akash:
      profile: app
      count: 1
