---
version: "2.0"
services:
  service-1:
    image: cvpfus/heurist-miner:0.11
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 8000
        as: 8000
        proto: tcp
        to:
          - global: true
    command:
      - sh
      - "-c"
    args: 
      - './install_flashattention.sh;
      ./llm-miner-starter.sh $MODEL_NAME; sleep infinity'
    env:
      - MODEL_NAME=openhermes-mixtral-8x7b-gptq
      - MINER_ID_0=0x544476DB6C3514a456e32F9436490B99395A3031
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 90Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
